############################
## Processing barcode counts for pool complexity
############################
# Contents:
# 1. Setting up the environment and reading in data --> line 9
# 2. Generating figures of read count distributions and sgRNA dropout upset --> line 40


#########################
# Setting up the environment
rm(list = ls()) #Clear environment of any existing variables or data
.libPaths('/projects/standard/selmecki/pvzande/MyRlibs_pvzande/') #set path for libraries
setwd("/projects/standard/selmecki/pvzande/CRISPRa/CRISPRaPaper/") #set working directory
#Load libraries
library(dplyr)
library(ggplot2)
library(UpSetR)
# Set path for figures
fig.dir <- "/projects/standard/selmecki/pvzande/CRISPRa/CRISPRaPaper/Figures/Updated"

# Reading in the .csv counts files generated by the "Assembledcounts.sh" scripts - there is data from two sequencing runs
filenamesrun1 <- list.files(path = "/projects/standard/selmecki/pvzande/CRISPRa/Selmecki_Project_002/counts2", pattern = "counts.csv", full.names = TRUE)
filenamesrun2 <- list.files(path = "/projects/standard/selmecki/pvzande/CRISPRa/Selmecki_Project_003/counts2", pattern = "counts.csv", full.names = TRUE)
filenamestogether <- c(filenamesrun1, filenamesrun2)

GETCOUNTS <- function(x) {
  countdf <- read.csv(x, header = 1)
  return(countdf)
}

countlist <- lapply(filenamestogether, GETCOUNTS)

samplenamesrun1 <- list.files(path = "/projects/standard/selmecki/pvzande/CRISPRa/Selmecki_Project_002/counts2", pattern = "counts.csv", full.names = FALSE)
samplenamesrun2 <- list.files(path = "/projects/standard/selmecki/pvzande/CRISPRa/Selmecki_Project_003/counts2", pattern = "counts.csv", full.names = FALSE)
samplenamestogether <- c(samplenamesrun1, samplenamesrun2)
samplenamestogether <- gsub(".csv","", samplenamestogether)

names(countlist) <- samplenamestogether

###########################
## Now plotting distributions of read counts for each pool, and comparing dropouts between each of them.

ggplot(data = countlist[["P75016_S52counts"]], aes(x = log2(Count))) +
  geom_histogram(binwidth = .2, fill = "grey") +
  theme_bw() +
  xlab(expr(log[2]~guide~count)) +
  ylab("Number of guides") +
  ggtitle("P75016")
ggsave("P75016hist.tiff", path = fig.dir, plot = last_plot(), width = 3, height = 3)
table(countlist[["P75016_S52counts"]]$Count < 1)
P75016DO <- countlist[["P75016_S52counts"]][which(countlist[["P75016_S52counts"]]$Count < 1),"Barcode"]

ggplot(data = countlist[["BFPGFP_S29counts"]], aes(x = log2(Count))) +
  geom_histogram(binwidth = .2, fill = "grey") +
  theme_bw() +
  xlab(expr(log[2]~guide~count)) +
  ylab("Number of guides") +
  ggtitle("AMS5192")
ggsave("BFPGFPhist.tiff", path = fig.dir, plot = last_plot(), width = 3, height = 3)
table(countlist[["BFPGFP_S29counts"]]$Count < 1)
BFPGFPDO <- countlist[["BFPGFP_S29counts"]][which(countlist[["BFPGFP_S29counts"]]$Count < 1),"Barcode"]

ggplot(data = countlist[["L26_S41counts"]], aes(x = log2(Count))) +
  geom_histogram(binwidth = .2, fill = "grey") +
  theme_bw() +
  xlab(expr(log[2]~guide~count)) +
  ylab("Number of guides") +
  ggtitle("L26")
ggsave("L26hist.tiff", path = fig.dir, plot = last_plot(), width = 3, height = 3)
table(countlist[["L26_S41counts"]]$Count < 1)
L26DO <- countlist[["L26_S41counts"]][which(countlist[["L26_S41counts"]]$Count < 1),"Barcode"]

ggplot(data = countlist[["P75063Pool1_S1_L001counts"]], aes(x = log2(Count))) +
  geom_histogram(binwidth = .2, fill = "grey") +
  theme_bw() +
  xlab(expr(log[2]~guide~count)) +
  ylab("Number of guides") +
  ggtitle("L26")
ggsave("P75063hist.tiff", path = fig.dir, plot = last_plot(), width = 3, height = 3)
table(countlist[["P75063Pool1_S1_L001counts"]]$Count < 1)
P75063DO <- countlist[["P75063Pool1_S1_L001counts"]][which(countlist[["P75063Pool1_S1_L001counts"]]$Count < 1),"Barcode"]

#Showing the expansion over the initial pool 
ggplot(data = countlist[["P75063Pool1_S1_L001counts"]], aes(x = log2(Count))) +
  geom_histogram(binwidth = .2, fill = "grey") +
  geom_histogram(data = countlist[["P75063Poolexpand_S3_L001counts"]], aes(x = log2(Count)), binwidth = .2, fill = "skyblue") +
  theme_bw() +
  xlab(expr(log[2]~guide~count)) +
  ylab("Number of barcodes") +
  ggtitle("Effect of overnight expansion")
ggsave("P75963ExpComp.tiff", path = fig.dir, plot = last_plot(), width = 3, height = 3)

#Drop out comparisons between the four genetic background pools
DOlist <- list(P75016DO, L26DO, BFPGFPDO, P75063DO) 
names(DOlist) <- c("P75016", "L26", "AMS5192", "P75063")

tiff(paste0(fig.dir,"/4PoolComp.tiff"), res = 300, width = 1000, height = 1000)
upset(fromList(DOlist), sets = c("P75016", "L26", "AMS5192", "P75063"))
dev.off()

